import type { Metadata } from "next";
import { Inter, Lato } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--inter-font",
  weight: ["300", "400", "600"],
});
const lato = Lato({
  subsets: ["latin"],
  display: "swap",
  variable: "--lato-font",
  weight: ["700"],
});

export const metadata: Metadata = {
  title: "Angela Smith",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${lato.variable} h-full overflow-auto`}
    >
      <body className="w-full h-full flex flex-col overflow-auto">
        {children}
      </body>
    </html>
  );
}
